### ISSUE TITLE
https://open-vsx.org/ Did not find it, VSCodium could not be installed

### ISSUE THREAD

**Issue by pgy866** [MrOrz/vscode-gettext#23] opened 2021-12-09 07:07 UTC
https://open-vsx.org
Did not find it, VSCodium could not be installed
没有发现它，无法安装

**Comment by GitMensch** [comment] 2022-10-18 07:28
It is actually published there since August 2021 so I _think_ this issue can be closed as duplicate of #12, which is in the process of being solved forever with #27.

**Comment by MrOrz** [comment] 2024-01-28 05:38
Fixed in #30

**Closed as completed by MrOrz** 2024-01-28 05:38 UTC
